In [ ]:
import s3fs
s3 = s3fs.S3FileSystem(anon=False)
import fwiVis.fwiVis as fv


from math import cos, asin, sqrt
import re
import dask ## Needed to install, but didn't update env

import numpy as np
import geopandas as gpd

import pandas as pd
from pandas.errors import SettingWithCopyWarning
from matplotlib import pyplot as plt
import os
import rioxarray as rio
import xarray as xr


from shapely.errors import ShapelyDeprecationWarning
from shapely.geometry import Point
from shapely import wkt
import warnings

import datetime
from datetime import date
import traceback

warnings.filterwarnings("ignore", category=ShapelyDeprecationWarning) 
warnings.filterwarnings("ignore", category=SettingWithCopyWarning) 
# SettingWithCopyWarning

#/projects/my-public-bucket/fire_spread/geom_CHEATSHEET_CONUS_NRT_2022_2023-03-13.csv

In [12]:
s3.ls("s3://veda-data-store-staging/EIS/CEOS_DATA")

['veda-data-store-staging/EIS/CEOS_DATA/CH4_FLUX',
 'veda-data-store-staging/EIS/CEOS_DATA/CO2_FLUX',
 'veda-data-store-staging/EIS/CEOS_DATA/CO2_flux_updated']

In [71]:
## Read in the cheatsheet 

cheatsheet = pd.read_csv("/projects/my-public-bucket/fire_spread/geom_CHEATSHEET_CONUS_NRT_2022_2023-03-13.csv", header = None)
# cheatsheet = cheatsheet[1:len(cheatsheet)]
# cheatsheet = cheatsheet.rename(columns= {"geometry": "none"})
cheatsheet = cheatsheet.rename(columns={1:"fireID",
                          2: "Lat", 
                          3: "Lon",
                         4: "geometry"})


cheatsheet['geometry'] = cheatsheet['geometry'].apply(wkt.loads)
gdf = gpd.GeoDataFrame(cheatsheet, crs='epsg:4326')
#cheatsheet = gpd.GeoDataFrame(cheatsheet,crs="EPSG:4326", geometry= "test")

In [66]:
cheatsheet

,0,fireID,Lat,Lon,geometry
0,0,24977,34.965700,-78.064619,POLYGON ((-78.07977627990043 34.95653020651644...
1,1,12176,27.663481,-81.373906,POLYGON ((-81.39577817131618 27.66630388272149...
2,2,4228,31.314731,-93.347009,"POLYGON ((-93.35410946887161 31.3105698699179,..."
3,3,15831,32.593701,-93.574322,POLYGON ((-93.59129117490413 32.58924720927194...
4,4,7763,33.813846,-85.592532,POLYGON ((-85.58833819922934 33.83189697651479...
...,...,...,...,...,...
875,875,9280,34.823634,-94.011562,"POLYGON ((-94.0317964458139 34.83304879798746,..."
876,876,20956,41.716912,-121.075634,POLYGON ((-121.08444389744604 41.7031194516363...
877,877,3985,30.220414,-82.560525,POLYGON ((-82.57754024009655 30.22136730282054...
878,878,14565,29.306490,-82.944323,POLYGON ((-82.93573606114234 29.29922036602926...
879,879,11732,33.175196,-79.528616,POLYGON ((-79.54555314913873 33.16145148028421...

In [79]:
#cheatsheet = cheatsheet.dropna()
#cheatsheet.geometry = cheatsheet.geometry.astype
#cheatsheet.set_geometry("geometry")
tmp = gdf[["fireID", "geometry"]]
tmp

     fireID                                           geometry
0     24977  POLYGON ((-78.07978 34.95653, -78.07982 34.956...
1     12176  POLYGON ((-81.39578 27.66630, -81.39590 27.666...
2      4228  POLYGON ((-93.35411 31.31057, -93.35276 31.320...
3     15831  POLYGON ((-93.59129 32.58925, -93.59131 32.589...
4      7763  POLYGON ((-85.58834 33.83190, -85.58828 33.831...
..      ...                                                ...
875    9280  POLYGON ((-94.03180 34.83305, -94.03167 34.833...
876   20956  POLYGON ((-121.08444 41.70312, -121.08466 41.7...
877    3985  POLYGON ((-82.57754 30.22137, -82.57764 30.221...
878   14565  POLYGON ((-82.93574 29.29922, -82.93578 29.299...
879   11732  POLYGON ((-79.54555 33.16145, -79.54636 33.164...

[880 rows x 2 columns]

In [83]:
#tmp.explore()

In [84]:
#cheatsheet.explore()